### ISSUE TITLE
2022-08-31，发现了RMX3562_11_A.44版本

### ISSUE THREAD

**Issue by aa51513** [chuest/ota_update#1]
OPPO Realme GT Neo3
发现了新版本

您能更新一下，或者告诉我如何自行下载吗？

**Comment by chuest** [comment]
好的，我晚上更新一下。

**Comment by chuest** [comment]
> OPPO Realme GT Neo3 发现了新版本
> 
> 您能更新一下，或者告诉我如何自行下载吗？

已更新。
