### ISSUE TITLE
OPPO Realme GT Neo3 extract payload.bin

### ISSUE THREAD

**Issue by 5n0wfish** [chuest/ota_update#2]
rom包中的 唯独 boot.img 使用以往的 payload_dump 工具无法解压，报加密算法错误。
您这有什么解决办法吗？

**Comment by chuest** [comment]
试一下该工具 [payload-dumper-go](https://github.com/ssut/payload-dumper-go) 是否可以解压

**Comment by 5n0wfish** [comment]
非常感谢
